models:
  - name: batting_team_win_probability
    model_type: sklearn.logistic_regression
    features:
      - current_innings_runs
      - current_innings_wickets
      - current_innings_legal_balls_remaining
      - current_innings_runs_required
    target_features:
      - batting_team_won
